### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by wushilian** [moskomule/ssl-suite#1]
in '/backends/utils.py"'
cannot import name 'exponential_moving_average_' from 'homura.modules' (/home/jasper/anaconda3/lib/python3.7/site-packages/homura/modules/__init__.py)

**Comment by moskomule** [comment]
Sorry, I didn't update homura's master.
So at the moment, please use `pip install -U git+https://github.com/moskomule/homura@dev`.

**Comment by wushilian** [comment]
thank u
